language: r

#be strict when checking our package
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: lXnNbm0BGZKlR3M2JaNyVTmQV771uXpt9y/z8Aa0FVf6HVn2ksnE/nqTuI4+Dq6S4GsjEeicIFNuF5Gh13XFqklGOY/cbVw3sNJiEeKVsMIINoieGLhnUOOWN2zRSLF0QP7l6lPfdHzGpEHBQYrtky4Og1VQ6f5KoC7SnoT69NM=
